baseURL: 'https://sredevops.dev'
title: SREDevOps.dev
languageCode: es-es
defaultContentLanguage: es
theme: hello-friend-ng
PygmentsCodeFences: true
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
copyright: >-
  This work is licensed under a Creative Commons Attribution-NonCommercial 4.0
  International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
enableMissingTranslationPlaceholders: false
disableRSS: false
disableSitemap: false
disable404: false
disableHugoGeneratorInject: false
permalinks:
  posts: '/posts/:year/:month/:title/'
author:
  name: Nicolás Georger
blackfriday:
  hrefTargetBlank: true
taxonomies:
  tag: tags
  category: categorias
  series: series
  pages: pages
params:
  # Logo:
  #   path: 'logo-h.png'
  #   alt: 'SREDevOps.dev'
  #   maxWidth: '500px'
  Portait:
    path: 'logo-h.png'
    alt: 'SREDevOps.dev'
    maxWidth: '200px'
  themeColor: 'black'
  dateform: '2 Jan 2006'
  dateformShort: 2 Jan
  dateformNum: '01-02-2006'
  dateformNumTime: '2006-01-02 15:04'
  description: >-
    Promovemos la cultura SRE/DevOps, con enfoque en Chile y América Latina, a
    través de facilitar comunidades y contextos de apoyo, orientación y
    aprendizaje.
  keywords: sre, SREDevOps, dev, chile, español
  images:
    - 'logo-h.png'
  homeSubtitle: 'Queremos construir "Curiosidad Continua" y "Comunidades como Soporte" para contribuir al ecosistema de las culturas, prácticas y tecnologías asociadas al concepto de "Site Reliability Engineering" , facilitando instancias para reunir personas que quieran aprender, enseñar, compartir, comunicar, enlazar y contribuir. 
      Latinoamérica y nuestro castellano, es el foco inicial, no-excluyente, con el propósito de facilitar el acercamiento al mundo cloud native.'
  disableReadOtherPosts: true
  enableThemeToggle: false
  enableSharingButtons: true
  enableGlobalLanguageMenu: false
  customCSS: []
  customJS: []
  justifyContent: true
  footer:
    trademark: false
    rss: true
    copyright: true
    author: true
    topText: []
    bottomText:
      - 'Construído con <a href="http://gohugo.io">Hugo</a>'
      - >-
        Theme basado en <a href="https://github.com/rhazdon">Djordje
        Atlialp</a>
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  logo:
    logoMark: 'usuario@sredevops.dev$'
    logoText: cd $HOME
    logoHomeLink: /

  social:
    # - name: twitter
    #   url: 'https://twitter.com/'
    - name: email
      url: 'mailto:info@sredevops.dev'
    - name: github
      url: 'https://github.com/sredevopsdev'
    - name: linkedin
      url: 'https://www.linkedin.com/company/sredevops/'
    # - name: stackoverflow
    #   url: 'https://www.stackoverflow.com/'
    - name: youtube
      url: 'https://www.youtube.com/@srdevopsdev'
    - name: discord
      url: 'https://discord.gg/bK9rXFTvpk'
    - id: rss
      name: rss
      url: /index.xml
languages:
  es:
    subtitle: Queremos construir "Curiosidad Continua" y "Comunidades como Soporte"
    weight: 1
    copyright: >-
      <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
  # en:
  #   subtitle: Hello Friend NG Theme
  #   weight: 2
  #   copyright: >-
  #     <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
  #     rel="noopener">CC BY-NC 4.0</a>
menu:
  main:
    - identifier: comunidad-discord
      name: Discord
      url: https://discord.gg/bK9rXFTvpk
    - identifier: github
      name: Github
      url: 'https://github.com/sredevopsdev'
    # - identifier: about
    #   name: About
    #   url: about/
    # - identifier: posts
    #   name: Posts
    #   url: posts/
